// =====================================================================
// AUTOGENERATED TINYML C HEADER - ZERO-HEAP STANDALONE INFERENCE ENGINE
// Generated for ESP32 Promiscuous Sniffer & Edge ML Detection
// 100% Deterministic: Trích xuất 1:1 từ mô hình đã huấn luyện (Zero-heuristic)
// =====================================================================

#ifndef TINYML_MODEL_H
#define TINYML_MODEL_H

#include <stdint.h>
#include <stdbool.h>
#include <math.h>
#include <string.h>

#define TINYML_IN_FEATURES 56
#define TINYML_NUM_CLASSES 15
#define TINYML_NORMAL_CLASS_IDX 7
#define TINYML_ANOMALY_THRESHOLD 0.042928f
#define TINYML_CLASSIFIER_NAME "EdgeDeepNet"
#define TINYML_ANOMALY_DETECTOR_NAME "AutoencoderNet"

/*
 * DANH SÁCH 56 ĐẶC TRƯNG MẠNG (FEATURES):
 *   [ 0] arp.opcode
 *   [ 1] arp.hw.size
 *   [ 2] icmp.checksum
 *   [ 3] icmp.seq_le
 *   [ 4] icmp.transmit_timestamp
 *   [ 5] icmp.unused
 *   [ 6] http.file_data
 *   [ 7] http.content_length
 *   [ 8] http.request.uri.query
 *   [ 9] http.request.method
 *   [10] http.referer
 *   [11] http.request.full_uri
 *   [12] http.request.version
 *   [13] http.response
 *   [14] http.tls_port
 *   [15] tcp.ack
 *   [16] tcp.ack_raw
 *   [17] tcp.checksum
 *   [18] tcp.connection.fin
 *   [19] tcp.connection.rst
 *   [20] tcp.connection.syn
 *   [21] tcp.connection.synack
 *   [22] tcp.dstport
 *   [23] tcp.flags
 *   [24] tcp.flags.ack
 *   [25] tcp.len
 *   [26] tcp.options
 *   [27] tcp.payload
 *   [28] tcp.seq
 *   [29] tcp.srcport
 *   [30] udp.port
 *   [31] udp.stream
 *   [32] udp.time_delta
 *   [33] dns.qry.name
 *   [34] dns.qry.name.len
 *   [35] dns.qry.qu
 *   [36] dns.qry.type
 *   [37] dns.retransmission
 *   [38] dns.retransmit_request
 *   [39] dns.retransmit_request_in
 *   [40] mqtt.conack.flags
 *   [41] mqtt.conflag.cleansess
 *   [42] mqtt.conflags
 *   [43] mqtt.hdrflags
 *   [44] mqtt.len
 *   [45] mqtt.msg_decoded_as
 *   [46] mqtt.msg
 *   [47] mqtt.msgtype
 *   [48] mqtt.proto_len
 *   [49] mqtt.protoname
 *   [50] mqtt.topic
 *   [51] mqtt.topic_len
 *   [52] mqtt.ver
 *   [53] mbtcp.len
 *   [54] mbtcp.trans_id
 *   [55] mbtcp.unit_id
 */

static const float TINYML_FEATURE_MEAN[56] = {
    0.003767f, 0.018277f, 1745.624553f, 1868.302052f, 1388.548841f, 0.000000f, 1.057047f, 4.798344f,
    1.876344f, 0.015591f, 0.000342f, 8.956624f, 0.027803f, 0.014762f, 0.000000f, 17321215.455178f,
    679302342.190472f, 29082.421806f, 0.087625f, 0.093231f, 0.070457f, 0.045124f, 26286.240787f, 14.383729f,
    0.737854f, 122.376502f, 0.773137f, 13710251.621633f, 8812431.898971f, 25829.627563f, 32.965474f, 73048.085462f,
    0.392336f, 1.689720f, 0.000072f, 0.057146f, 0.000000f, 0.012680f, 0.000018f, 0.000018f,
    28.376781f, 0.037671f, 0.075342f, 12.049783f, 1.996774f, 0.000000f, 2.243311f, 0.753111f,
    0.150684f, 0.037671f, 0.037689f, 0.904534f, 0.150684f, 0.001406f, 0.005479f, 0.000135f
};

static const float TINYML_FEATURE_SCALE[56] = {
    0.072075f, 0.330645f, 8607.382004f, 8804.280587f, 327060.210217f, 1.000000f, 11.672800f, 55.961210f,
    27.142313f, 0.132261f, 0.025471f, 84.032994f, 0.230849f, 0.120599f, 1.000000f, 111229041.013441f,
    438839365.061291f, 20684.498220f, 0.282749f, 0.290756f, 0.255916f, 0.207576f, 27497.063688f, 8.248773f,
    0.439802f, 463.915748f, 64.279919f, 113077704.149522f, 33976660.720643f, 26469.078320f, 1265.283932f, 368445.462882f,
    12.069574f, 26.012010f, 0.008491f, 5.212530f, 1.000000f, 0.583732f, 0.004245f, 0.004245f,
    6683.891605f, 0.190399f, 0.380798f, 43.361671f, 7.675419f, 1.000000f, 13.177367f, 2.710104f,
    0.761596f, 0.190399f, 0.190443f, 4.570627f, 0.761596f, 0.173230f, 0.672231f, 0.020580f
};

static const char* const TINYML_CLASS_NAMES[15] = {
    "Backdoor",
    "DDoS_HTTP",
    "DDoS_ICMP",
    "DDoS_TCP",
    "DDoS_UDP",
    "Fingerprinting",
    "MITM",
    "Normal",
    "Password",
    "Port_Scanning",
    "Ransomware",
    "SQL_injection",
    "Uploading",
    "Vulnerability_scanner",
    "XSS"
};

static inline void tinyml_standardize_features(const float* raw_features, float* out_features) {
    if (!raw_features || !out_features) return;
    for (int i = 0; i < TINYML_IN_FEATURES; i++) {
        float s = TINYML_FEATURE_SCALE[i];
        if (s != 0.0f) {
            out_features[i] = (raw_features[i] - TINYML_FEATURE_MEAN[i]) / s;
        } else {
            out_features[i] = raw_features[i] - TINYML_FEATURE_MEAN[i];
        }
    }
}

static inline const char* tinyml_get_threat_name(int class_idx) {
    if (class_idx >= 0 && class_idx < TINYML_NUM_CLASSES) {
        return TINYML_CLASS_NAMES[class_idx];
    }
    return "Unknown";
}

// =====================================================================
// TIER 1: ANOMALY DETECTION ENGINE (AutoencoderNet)
// =====================================================================
// --- Deep Autoencoder Anomaly Detector (TensorFlow Lite Engine) ---
// Lưu ý: Toàn bộ trọng số Autoencoder được biên dịch thành
// TensorFlow Lite FlatBuffer trong g_anomaly_tflite[] (xem tinyml_tflite_array.h).
#define TINYML_ANOMALY_IS_DL 1
#if __has_include("tinyml_tflite_array.h")
  #include "tinyml_tflite_array.h"
#endif

static inline float tinyml_predict_anomaly(const float* raw_features, bool* out_is_anomaly) {
    if (out_is_anomaly) *out_is_anomaly = false;
    return 0.0f;
}

// =====================================================================
// TIER 2: ATTACK CLASSIFIER ENGINE (EdgeDeepNet)
// =====================================================================
// --- Deep Learning Multi-Class Classifier (EdgeDeepNet DNN) ---
// Lưu ý: Toàn bộ trọng số và đồ thị mạng nơ-ron sâu được biên dịch thành
// TensorFlow Lite FlatBuffer trong g_classifier_tflite[] (xem tinyml_tflite_array.h).
#define TINYML_CLASSIFIER_IS_DL 1
#if __has_include("tinyml_tflite_array.h")
  #include "tinyml_tflite_array.h"
#endif

static inline int tinyml_predict_classifier(const float* raw_features, float* out_confidence) {
    if (out_confidence) *out_confidence = 1.0f;
    return TINYML_NORMAL_CLASS_IDX;
}

#endif // TINYML_MODEL_H
