// =====================================================================
// AUTOGENERATED TINYML C HEADER - ZERO-HEAP STANDALONE INFERENCE ENGINE
// Generated for ESP32 Promiscuous Sniffer & Edge ML Detection
// 100% Deterministic: Trích xuất 1:1 từ mô hình đã huấn luyện (Zero-heuristic)
// =====================================================================

#ifndef TINYML_MODEL_H
#define TINYML_MODEL_H

#include <stdint.h>
#include <stdbool.h>
#include <math.h>
#include <string.h>

#define TINYML_IN_FEATURES 56
#define TINYML_NUM_CLASSES 15
#define TINYML_NORMAL_CLASS_IDX 0
#define TINYML_ANOMALY_THRESHOLD 0.500000f
#define TINYML_CLASSIFIER_NAME "EdgeDeepNet"
#define TINYML_ANOMALY_DETECTOR_NAME "IsolationForest"

/*
 * DANH SÁCH 56 ĐẶC TRƯNG MẠNG (FEATURES):
 *   [ 0] arp.opcode
 *   [ 1] arp.hw.size
 *   [ 2] icmp.checksum
 *   [ 3] icmp.seq_le
 *   [ 4] icmp.transmit_timestamp
 *   [ 5] icmp.unused
 *   [ 6] http.file_data
 *   [ 7] http.content_length
 *   [ 8] http.request.uri.query
 *   [ 9] http.request.method
 *   [10] http.referer
 *   [11] http.request.full_uri
 *   [12] http.request.version
 *   [13] http.response
 *   [14] http.tls_port
 *   [15] tcp.ack
 *   [16] tcp.ack_raw
 *   [17] tcp.checksum
 *   [18] tcp.connection.fin
 *   [19] tcp.connection.rst
 *   [20] tcp.connection.syn
 *   [21] tcp.connection.synack
 *   [22] tcp.dstport
 *   [23] tcp.flags
 *   [24] tcp.flags.ack
 *   [25] tcp.len
 *   [26] tcp.options
 *   [27] tcp.payload
 *   [28] tcp.seq
 *   [29] tcp.srcport
 *   [30] udp.port
 *   [31] udp.stream
 *   [32] udp.time_delta
 *   [33] dns.qry.name
 *   [34] dns.qry.name.len
 *   [35] dns.qry.qu
 *   [36] dns.qry.type
 *   [37] dns.retransmission
 *   [38] dns.retransmit_request
 *   [39] dns.retransmit_request_in
 *   [40] mqtt.conack.flags
 *   [41] mqtt.conflag.cleansess
 *   [42] mqtt.conflags
 *   [43] mqtt.hdrflags
 *   [44] mqtt.len
 *   [45] mqtt.msg_decoded_as
 *   [46] mqtt.msg
 *   [47] mqtt.msgtype
 *   [48] mqtt.proto_len
 *   [49] mqtt.protoname
 *   [50] mqtt.topic
 *   [51] mqtt.topic_len
 *   [52] mqtt.ver
 *   [53] mbtcp.len
 *   [54] mbtcp.trans_id
 *   [55] mbtcp.unit_id
 */

static const float TINYML_FEATURE_MEAN[56] = {
    0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
    0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
    0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
    0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
    0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
    0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f,
    0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f
};

static const float TINYML_FEATURE_SCALE[56] = {
    1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f,
    1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f,
    1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f,
    1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f,
    1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f,
    1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f,
    1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f
};

static const char* const TINYML_CLASS_NAMES[15] = {
    "Normal",
    "DDoS_UDP",
    "DDoS_ICMP",
    "Ransomware",
    "DDoS_HTTP",
    "SQL_injection",
    "Uploading",
    "DDoS_TCP",
    "Backdoor",
    "Vulnerability_scanner",
    "Port_Scanning",
    "XSS",
    "Password",
    "MITM",
    "Fingerprinting"
};

static inline void tinyml_standardize_features(const float* raw_features, float* out_features) {
    if (!raw_features || !out_features) return;
    for (int i = 0; i < TINYML_IN_FEATURES; i++) {
        float s = TINYML_FEATURE_SCALE[i];
        if (s != 0.0f) {
            out_features[i] = (raw_features[i] - TINYML_FEATURE_MEAN[i]) / s;
        } else {
            out_features[i] = raw_features[i] - TINYML_FEATURE_MEAN[i];
        }
    }
}

static inline const char* tinyml_get_threat_name(int class_idx) {
    if (class_idx >= 0 && class_idx < TINYML_NUM_CLASSES) {
        return TINYML_CLASS_NAMES[class_idx];
    }
    return "Unknown";
}

// =====================================================================
// TIER 1: ANOMALY DETECTION ENGINE (IsolationForest)
// =====================================================================
// --- Isolation Forest Anomaly Detection Engine (10 iTrees) ---
#define TINYML_NUM_ITREES 10
#define TINYML_IFOREST_CN 10.24477f

static inline float tinyml_itree_0(const float* f) {
    if (f[29] <= -0.06262f) {
        if (f[17] <= 0.11319f) {
            if (f[43] <= 0.04758f) {
                if (f[19] <= 1.60284f) {
                    if (f[18] <= 0.67228f) {
                        if (f[25] <= 0.91441f) {
                            if (f[21] <= 2.22581f) {
                                if (f[16] <= -0.18573f) {
                                    return 9.0000f;
                                } else {
                                    return 11.7066f;
                                }
                            } else {
                                if (f[17] <= -0.32655f) {
                                    return 10.8517f;
                                } else {
                                    return 9.0000f;
                                }
                            }
                        } else {
                            if (f[25] <= 1.00316f) {
                                return 8.0000f;
                            } else {
                                if (f[17] <= -0.34876f) {
                                    return 9.0000f;
                                } else {
                                    return 10.0000f;
                                }
                            }
                        }
                    } else {
                        if (f[17] <= -0.35135f) {
                            return 7.0000f;
                        } else {
                            if (f[17] <= -0.09028f) {
                                return 8.0000f;
                            } else {
                                return 8.0000f;
                            }
                        }
                    }
                } else {
                    if (f[17] <= -0.73027f) {
                        if (f[17] <= -0.84862f) {
                            return 7.0000f;
                        } else {
                            return 7.0000f;
                        }
                    } else {
                        if (f[17] <= -0.09460f) {
                            if (f[22] <= 1.57659f) {
                                if (f[17] <= -0.25501f) {
                                    return 9.0000f;
                                } else {
                                    return 9.0000f;
                                }
                            } else {
                                return 8.0000f;
                            }
                        } else {
                            return 7.0000f;
                        }
                    }
                }
            } else {
                if (f[22] <= 1.44164f) {
                    return 5.0000f;
                } else {
                    return 5.0000f;
                }
            }
        } else {
            if (f[3] <= -0.28184f) {
                if (f[19] <= 2.66815f) {
                    if (f[29] <= -0.82952f) {
                        if (f[28] <= -0.12167f) {
                            if (f[18] <= 1.36687f) {
                                if (f[16] <= 0.50766f) {
                                    return 9.0000f;
                                } else {
                                    return 10.0000f;
                                }
                            } else {
                                return 8.0000f;
                            }
                        } else {
                            if (f[3] <= -0.28326f) {
                                if (f[15] <= -0.24797f) {
                                    return 18.5403f;
                                } else {
                                    return 10.0000f;
                                }
                            } else {
                                if (f[3] <= -0.28194f) {
                                    return 10.2074f;
                                } else {
                                    return 9.0000f;
                                }
                            }
                        }
                    } else {
                        if (f[15] <= -0.24655f) {
                            if (f[28] <= 3.98664f) {
                                return 8.0000f;
                            } else {
                                return 8.0000f;
                            }
                        } else {
                            if (f[15] <= -0.24530f) {
                                return 8.0000f;
                            } else {
                                return 8.0000f;
                            }
                        }
                    }
                } else {
                    if (f[17] <= 1.33533f) {
                        return 6.0000f;
                    } else {
                        if (f[22] <= 1.92166f) {
                            return 7.0000f;
                        } else {
                            return 7.0000f;
                        }
                    }
                }
            } else {
                if (f[3] <= -0.28118f) {
                    return 5.0000f;
                } else {
                    return 5.0000f;
                }
            }
        }
    } else {
        if (f[44] <= 3.36302f) {
            if (f[18] <= 1.13033f) {
                if (f[20] <= 1.23337f) {
                    if (f[17] <= 1.03500f) {
                        if (f[16] <= 0.17139f) {
                            return 7.0000f;
                        } else {
                            if (f[28] <= -0.11653f) {
                                if (f[28] <= -0.12167f) {
                                    return 9.0000f;
                                } else {
                                    return 11.3270f;
                                }
                            } else {
                                return 8.0000f;
                            }
                        }
                    } else {
                        if (f[16] <= 0.28401f) {
                            if (f[16] <= -0.67884f) {
                                return 8.0000f;
                            } else {
                                return 8.0000f;
                            }
                        } else {
                            if (f[29] <= 1.42357f) {
                                return 8.0000f;
                            } else {
                                return 8.0000f;
                            }
                        }
                    }
                } else {
                    if (f[17] <= -0.46750f) {
                        return 6.0000f;
                    } else {
                        if (f[29] <= 1.52290f) {
                            if (f[17] <= 0.44031f) {
                                if (f[29] <= 1.21614f) {
                                    return 9.0000f;
                                } else {
                                    return 10.0000f;
                                }
                            } else {
                                return 8.0000f;
                            }
                        } else {
                            if (f[17] <= 0.76390f) {
                                return 8.0000f;
                            } else {
                                return 8.0000f;
                            }
                        }
                    }
                }
            } else {
                if (f[17] <= 0.57457f) {
                    if (f[16] <= -0.02518f) {
                        return 6.0000f;
                    } else {
                        return 6.0000f;
                    }
                } else {
                    if (f[29] <= 1.26738f) {
                        return 6.0000f;
                    } else {
                        if (f[29] <= 1.75307f) {
                            return 7.0000f;
                        } else {
                            return 7.0000f;
                        }
                    }
                }
            }
        } else {
            if (f[46] <= 0.06384f) {
                if (f[17] <= 0.85732f) {
                    return 5.0000f;
                } else {
                    if (f[17] <= 1.31575f) {
                        return 6.0000f;
                    } else {
                        return 6.0000f;
                    }
                }
            } else {
                if (f[17] <= 0.14947f) {
                    if (f[17] <= -0.11746f) {
                        return 6.0000f;
                    } else {
                        return 6.0000f;
                    }
                } else {
                    return 5.0000f;
                }
            }
        }
    }
}

static inline float tinyml_itree_1(const float* f) {
    if (f[2] <= -0.27340f) {
        if (f[29] <= -0.18871f) {
            if (f[19] <= 2.31836f) {
                if (f[47] <= 1.04856f) {
                    if (f[21] <= 2.62823f) {
                        if (f[32] <= -0.03422f) {
                            if (f[29] <= -0.75628f) {
                                if (f[16] <= 0.58888f) {
                                    return 10.2074f;
                                } else {
                                    return 18.6798f;
                                }
                            } else {
                                if (f[25] <= 0.98744f) {
                                    return 9.0000f;
                                } else {
                                    return 12.0237f;
                                }
                            }
                        } else {
                            if (f[32] <= -0.03419f) {
                                return 8.0000f;
                            } else {
                                if (f[25] <= 0.37931f) {
                                    return 9.0000f;
                                } else {
                                    return 9.0000f;
                                }
                            }
                        }
                    } else {
                        if (f[17] <= 0.07969f) {
                            if (f[17] <= -0.15789f) {
                                if (f[22] <= 1.71732f) {
                                    return 9.0000f;
                                } else {
                                    return 9.0000f;
                                }
                            } else {
                                return 8.0000f;
                            }
                        } else {
                            return 7.0000f;
                        }
                    }
                } else {
                    if (f[17] <= 0.40289f) {
                        return 6.0000f;
                    } else {
                        if (f[22] <= 1.56703f) {
                            return 7.0000f;
                        } else {
                            return 7.0000f;
                        }
                    }
                }
            } else {
                if (f[17] <= 0.56624f) {
                    if (f[17] <= 0.20095f) {
                        if (f[17] <= -0.24032f) {
                            return 7.0000f;
                        } else {
                            return 7.0000f;
                        }
                    } else {
                        return 6.0000f;
                    }
                } else {
                    return 5.0000f;
                }
            }
        } else {
            if (f[42] <= 4.38216f) {
                if (f[22] <= -0.58971f) {
                    if (f[25] <= -0.08193f) {
                        if (f[18] <= 3.17656f) {
                            if (f[16] <= -0.72790f) {
                                if (f[15] <= -0.24797f) {
                                    return 11.3270f;
                                } else {
                                    return 9.0000f;
                                }
                            } else {
                                if (f[17] <= 0.30852f) {
                                    return 12.7489f;
                                } else {
                                    return 12.2963f;
                                }
                            }
                        } else {
                            if (f[17] <= -0.16525f) {
                                return 8.0000f;
                            } else {
                                return 8.0000f;
                            }
                        }
                    } else {
                        if (f[17] <= -0.12235f) {
                            if (f[46] <= 6.43161f) {
                                return 8.0000f;
                            } else {
                                return 8.0000f;
                            }
                        } else {
                            return 7.0000f;
                        }
                    }
                } else {
                    if (f[17] <= 0.09527f) {
                        if (f[15] <= -0.08341f) {
                            return 7.0000f;
                        } else {
                            return 7.0000f;
                        }
                    } else {
                        if (f[17] <= 1.36541f) {
                            return 7.0000f;
                        } else {
                            if (f[28] <= -0.07612f) {
                                return 8.0000f;
                            } else {
                                return 8.0000f;
                            }
                        }
                    }
                }
            } else {
                return 4.0000f;
            }
        }
    } else {
        if (f[25] <= 0.19333f) {
            if (f[25] <= 0.10271f) {
                return 4.0000f;
            } else {
                return 4.0000f;
            }
        } else {
            return 3.0000f;
        }
    }
}

static inline float tinyml_itree_2(const float* f) {
    if (f[18] <= 2.20046f) {
        if (f[32] <= -0.03417f) {
            if (f[16] <= -0.08484f) {
                if (f[20] <= -0.09020f) {
                    if (f[22] <= 1.40404f) {
                        if (f[16] <= -1.35721f) {
                            if (f[22] <= 1.36699f) {
                                return 8.0000f;
                            } else {
                                if (f[17] <= 0.92995f) {
                                    return 9.0000f;
                                } else {
                                    return 9.0000f;
                                }
                            }
                        } else {
                            return 7.0000f;
                        }
                    } else {
                        if (f[17] <= -0.33008f) {
                            if (f[17] <= -1.09418f) {
                                return 8.0000f;
                            } else {
                                if (f[22] <= 1.62256f) {
                                    return 9.0000f;
                                } else {
                                    return 9.0000f;
                                }
                            }
                        } else {
                            if (f[17] <= 0.13090f) {
                                if (f[19] <= 0.53397f) {
                                    return 9.0000f;
                                } else {
                                    return 10.8517f;
                                }
                            } else {
                                if (f[22] <= 1.44823f) {
                                    return 9.0000f;
                                } else {
                                    return 10.0000f;
                                }
                            }
                        }
                    }
                } else {
                    if (f[29] <= 1.56436f) {
                        if (f[17] <= 1.60778f) {
                            if (f[29] <= 1.41364f) {
                                return 8.0000f;
                            } else {
                                return 8.0000f;
                            }
                        } else {
                            return 7.0000f;
                        }
                    } else {
                        if (f[17] <= 0.45998f) {
                            return 7.0000f;
                        } else {
                            return 7.0000f;
                        }
                    }
                }
            } else {
                if (f[43] <= 0.65911f) {
                    if (f[29] <= 0.48673f) {
                        if (f[23] <= 1.13661f) {
                            if (f[21] <= 0.46445f) {
                                if (f[29] <= -0.75844f) {
                                    return 18.7410f;
                                } else {
                                    return 12.0237f;
                                }
                            } else {
                                if (f[22] <= 1.75721f) {
                                    return 10.2074f;
                                } else {
                                    return 9.0000f;
                                }
                            }
                        } else {
                            return 7.0000f;
                        }
                    } else {
                        if (f[22] <= -0.57344f) {
                            if (f[28] <= -0.12167f) {
                                return 8.0000f;
                            } else {
                                if (f[29] <= 1.26106f) {
                                    return 10.2074f;
                                } else {
                                    return 12.2963f;
                                }
                            }
                        } else {
                            if (f[17] <= 0.89377f) {
                                if (f[15] <= 0.36642f) {
                                    return 9.0000f;
                                } else {
                                    return 9.0000f;
                                }
                            } else {
                                return 8.0000f;
                            }
                        }
                    }
                } else {
                    if (f[46] <= 11.92628f) {
                        if (f[17] <= 1.00607f) {
                            if (f[17] <= -0.57248f) {
                                return 8.0000f;
                            } else {
                                return 8.0000f;
                            }
                        } else {
                            return 7.0000f;
                        }
                    } else {
                        return 6.0000f;
                    }
                }
            }
        } else {
            return 3.0000f;
        }
    } else {
        if (f[15] <= -0.24797f) {
            if (f[29] <= 1.27386f) {
                return 4.0000f;
            } else {
                return 4.0000f;
            }
        } else {
            if (f[22] <= 1.54356f) {
                return 4.0000f;
            } else {
                if (f[17] <= 0.93834f) {
                    return 5.0000f;
                } else {
                    return 5.0000f;
                }
            }
        }
    }
}

static inline float tinyml_itree_3(const float* f) {
    if (f[44] <= 1.14550f) {
        if (f[25] <= 0.34115f) {
            if (f[17] <= -0.73093f) {
                if (f[18] <= 2.57191f) {
                    if (f[23] <= -0.85427f) {
                        return 7.0000f;
                    } else {
                        if (f[28] <= -0.12167f) {
                            if (f[47] <= 1.21449f) {
                                if (f[22] <= 1.74966f) {
                                    return 9.0000f;
                                } else {
                                    return 9.0000f;
                                }
                            } else {
                                return 8.0000f;
                            }
                        } else {
                            return 7.0000f;
                        }
                    }
                } else {
                    if (f[29] <= 0.80286f) {
                        return 6.0000f;
                    } else {
                        return 6.0000f;
                    }
                }
            } else {
                if (f[21] <= 2.83911f) {
                    if (f[22] <= 0.93370f) {
                        if (f[28] <= -0.11512f) {
                            if (f[22] <= -0.71719f) {
                                if (f[25] <= -0.02653f) {
                                    return 15.4809f;
                                } else {
                                    return 14.5088f;
                                }
                            } else {
                                if (f[47] <= 1.40504f) {
                                    return 13.6955f;
                                } else {
                                    return 10.8517f;
                                }
                            }
                        } else {
                            return 7.0000f;
                        }
                    } else {
                        if (f[2] <= -0.27343f) {
                            if (f[28] <= 1.07132f) {
                                if (f[23] <= -0.36261f) {
                                    return 10.2074f;
                                } else {
                                    return 17.6957f;
                                }
                            } else {
                                return 8.0000f;
                            }
                        } else {
                            if (f[3] <= -0.27995f) {
                                if (f[3] <= -0.28195f) {
                                    return 11.7066f;
                                } else {
                                    return 9.0000f;
                                }
                            } else {
                                return 8.0000f;
                            }
                        }
                    }
                } else {
                    if (f[17] <= 1.01582f) {
                        if (f[17] <= -0.03186f) {
                            if (f[17] <= -0.58504f) {
                                return 8.0000f;
                            } else {
                                return 8.0000f;
                            }
                        } else {
                            return 7.0000f;
                        }
                    } else {
                        return 6.0000f;
                    }
                }
            }
        } else {
            if (f[25] <= 0.80177f) {
                if (f[29] <= -0.78657f) {
                    if (f[3] <= -0.27808f) {
                        if (f[22] <= 0.13361f) {
                            if (f[32] <= -0.03417f) {
                                if (f[31] <= -0.25711f) {
                                    return 12.7489f;
                                } else {
                                    return 10.0000f;
                                }
                            } else {
                                return 8.0000f;
                            }
                        } else {
                            if (f[32] <= -0.03262f) {
                                if (f[25] <= 0.39448f) {
                                    return 9.0000f;
                                } else {
                                    return 10.2074f;
                                }
                            } else {
                                return 8.0000f;
                            }
                        }
                    } else {
                        return 6.0000f;
                    }
                } else {
                    return 5.0000f;
                }
            } else {
                if (f[17] <= 0.64038f) {
                    if (f[17] <= -0.68557f) {
                        return 6.0000f;
                    } else {
                        return 6.0000f;
                    }
                } else {
                    if (f[17] <= 0.98449f) {
                        return 6.0000f;
                    } else {
                        if (f[17] <= 1.45639f) {
                            return 7.0000f;
                        } else {
                            return 7.0000f;
                        }
                    }
                }
            }
        }
    } else {
        if (f[44] <= 5.67521f) {
            if (f[16] <= -0.38318f) {
                return 4.0000f;
            } else {
                return 4.0000f;
            }
        } else {
            if (f[46] <= 7.94377f) {
                return 4.0000f;
            } else {
                if (f[17] <= 0.68661f) {
                    return 5.0000f;
                } else {
                    return 5.0000f;
                }
            }
        }
    }
}

static inline float tinyml_itree_4(const float* f) {
    if (f[49] <= 3.68780f) {
        if (f[44] <= 2.63728f) {
            if (f[15] <= -0.07481f) {
                if (f[43] <= 0.43744f) {
                    if (f[16] <= -1.32958f) {
                        if (f[20] <= 0.01700f) {
                            if (f[22] <= 1.52302f) {
                                if (f[22] <= 1.32837f) {
                                    return 9.0000f;
                                } else {
                                    return 9.0000f;
                                }
                            } else {
                                if (f[17] <= 0.24198f) {
                                    return 9.0000f;
                                } else {
                                    return 10.0000f;
                                }
                            }
                        } else {
                            if (f[29] <= 1.36648f) {
                                if (f[29] <= 1.26955f) {
                                    return 9.0000f;
                                } else {
                                    return 9.0000f;
                                }
                            } else {
                                if (f[17] <= -0.06535f) {
                                    return 9.0000f;
                                } else {
                                    return 10.0000f;
                                }
                            }
                        }
                    } else {
                        if (f[22] <= 0.26508f) {
                            if (f[16] <= 0.40241f) {
                                if (f[29] <= 1.39936f) {
                                    return 9.0000f;
                                } else {
                                    return 9.0000f;
                                }
                            } else {
                                if (f[25] <= 0.09321f) {
                                    return 16.2402f;
                                } else {
                                    return 15.0849f;
                                }
                            }
                        } else {
                            if (f[29] <= -0.77136f) {
                                if (f[21] <= 2.07313f) {
                                    return 17.9048f;
                                } else {
                                    return 11.3270f;
                                }
                            } else {
                                if (f[23] <= 0.95012f) {
                                    return 11.7066f;
                                } else {
                                    return 10.0000f;
                                }
                            }
                        }
                    }
                } else {
                    if (f[16] <= 0.82207f) {
                        return 6.0000f;
                    } else {
                        if (f[22] <= 1.44733f) {
                            return 7.0000f;
                        } else {
                            if (f[17] <= 1.39725f) {
                                if (f[17] <= 0.47481f) {
                                    return 9.0000f;
                                } else {
                                    return 9.0000f;
                                }
                            } else {
                                return 8.0000f;
                            }
                        }
                    }
                }
            } else {
                return 4.0000f;
            }
        } else {
            return 3.0000f;
        }
    } else {
        if (f[17] <= 0.24023f) {
            if (f[16] <= -0.12591f) {
                return 4.0000f;
            } else {
                if (f[29] <= 1.53037f) {
                    return 5.0000f;
                } else {
                    return 5.0000f;
                }
            }
        } else {
            return 3.0000f;
        }
    }
}

static inline float tinyml_itree_5(const float* f) {
    if (f[27] <= -0.12748f) {
        if (f[47] <= 9.20037f) {
            if (f[22] <= 0.75447f) {
                if (f[28] <= -0.09269f) {
                    if (f[29] <= 0.32571f) {
                        if (f[32] <= -0.03407f) {
                            if (f[25] <= 0.46856f) {
                                if (f[31] <= -0.25505f) {
                                    return 16.8157f;
                                } else {
                                    return 9.0000f;
                                }
                            } else {
                                if (f[25] <= 0.53589f) {
                                    return 10.2074f;
                                } else {
                                    return 10.8517f;
                                }
                            }
                        } else {
                            return 7.0000f;
                        }
                    } else {
                        if (f[16] <= -0.83711f) {
                            return 7.0000f;
                        } else {
                            if (f[25] <= -0.08447f) {
                                if (f[17] <= -0.73724f) {
                                    return 9.0000f;
                                } else {
                                    return 13.4272f;
                                }
                            } else {
                                return 8.0000f;
                            }
                        }
                    }
                } else {
                    return 5.0000f;
                }
            } else {
                if (f[22] <= 1.52042f) {
                    if (f[23] <= -0.60075f) {
                        if (f[17] <= 0.98513f) {
                            if (f[17] <= 0.10488f) {
                                if (f[17] <= -0.35741f) {
                                    return 9.0000f;
                                } else {
                                    return 9.0000f;
                                }
                            } else {
                                if (f[17] <= 0.20878f) {
                                    return 9.0000f;
                                } else {
                                    return 9.0000f;
                                }
                            }
                        } else {
                            return 7.0000f;
                        }
                    } else {
                        if (f[28] <= -0.12167f) {
                            if (f[21] <= 0.08161f) {
                                if (f[16] <= 0.34293f) {
                                    return 9.0000f;
                                } else {
                                    return 9.0000f;
                                }
                            } else {
                                if (f[17] <= -0.20957f) {
                                    return 9.0000f;
                                } else {
                                    return 9.0000f;
                                }
                            }
                        } else {
                            if (f[15] <= -0.24797f) {
                                if (f[3] <= -0.28438f) {
                                    return 17.4431f;
                                } else {
                                    return 12.7489f;
                                }
                            } else {
                                if (f[28] <= -0.12167f) {
                                    return 10.8517f;
                                } else {
                                    return 9.0000f;
                                }
                            }
                        }
                    }
                } else {
                    if (f[28] <= 8.28460f) {
                        if (f[23] <= -0.89240f) {
                            return 7.0000f;
                        } else {
                            if (f[18] <= 2.17974f) {
                                if (f[23] <= 0.91453f) {
                                    return 13.1169f;
                                } else {
                                    return 9.0000f;
                                }
                            } else {
                                if (f[17] <= -0.33218f) {
                                    return 9.0000f;
                                } else {
                                    return 9.0000f;
                                }
                            }
                        }
                    } else {
                        if (f[25] <= 0.56612f) {
                            return 7.0000f;
                        } else {
                            if (f[28] <= 11.38861f) {
                                return 8.0000f;
                            } else {
                                return 8.0000f;
                            }
                        }
                    }
                }
            }
        } else {
            if (f[29] <= 1.66263f) {
                if (f[17] <= -0.32687f) {
                    return 5.0000f;
                } else {
                    return 5.0000f;
                }
            } else {
                if (f[29] <= 1.70846f) {
                    return 5.0000f;
                } else {
                    return 5.0000f;
                }
            }
        }
    } else {
        if (f[22] <= 1.73411f) {
            return 3.0000f;
        } else {
            return 3.0000f;
        }
    }
}

static inline float tinyml_itree_6(const float* f) {
    if (f[48] <= 4.35951f) {
        if (f[47] <= 7.08767f) {
            if (f[18] <= 3.44055f) {
                if (f[24] <= -0.03449f) {
                    if (f[23] <= -1.13733f) {
                        if (f[29] <= 1.39476f) {
                            if (f[29] <= 1.16205f) {
                                return 8.0000f;
                            } else {
                                if (f[17] <= -0.05749f) {
                                    return 9.0000f;
                                } else {
                                    return 10.0000f;
                                }
                            }
                        } else {
                            if (f[17] <= 0.62607f) {
                                return 8.0000f;
                            } else {
                                return 8.0000f;
                            }
                        }
                    } else {
                        if (f[17] <= 0.43297f) {
                            if (f[17] <= -0.80561f) {
                                return 8.0000f;
                            } else {
                                if (f[17] <= 0.01804f) {
                                    return 9.0000f;
                                } else {
                                    return 10.2074f;
                                }
                            }
                        } else {
                            return 7.0000f;
                        }
                    }
                } else {
                    if (f[29] <= 0.28139f) {
                        if (f[2] <= -0.27338f) {
                            if (f[27] <= -0.12867f) {
                                if (f[17] <= -0.69698f) {
                                    return 12.0237f;
                                } else {
                                    return 18.7004f;
                                }
                            } else {
                                if (f[17] <= 0.26019f) {
                                    return 9.0000f;
                                } else {
                                    return 10.0000f;
                                }
                            }
                        } else {
                            if (f[25] <= 0.33520f) {
                                if (f[25] <= 0.15256f) {
                                    return 9.0000f;
                                } else {
                                    return 9.0000f;
                                }
                            } else {
                                return 8.0000f;
                            }
                        }
                    } else {
                        if (f[51] <= 5.02716f) {
                            if (f[29] <= 1.16047f) {
                                if (f[29] <= 1.13502f) {
                                    return 9.0000f;
                                } else {
                                    return 9.0000f;
                                }
                            } else {
                                if (f[22] <= -0.55746f) {
                                    return 13.5659f;
                                } else {
                                    return 11.3270f;
                                }
                            }
                        } else {
                            if (f[46] <= 12.76774f) {
                                return 8.0000f;
                            } else {
                                return 8.0000f;
                            }
                        }
                    }
                }
            } else {
                if (f[17] <= 0.87298f) {
                    return 5.0000f;
                } else {
                    if (f[22] <= 1.54163f) {
                        return 6.0000f;
                    } else {
                        return 6.0000f;
                    }
                }
            }
        } else {
            if (f[29] <= 1.32608f) {
                if (f[29] <= 1.25798f) {
                    return 5.0000f;
                } else {
                    return 5.0000f;
                }
            } else {
                return 4.0000f;
            }
        }
    } else {
        if (f[17] <= 0.27181f) {
            if (f[17] <= -0.50760f) {
                return 4.0000f;
            } else {
                return 4.0000f;
            }
        } else {
            if (f[29] <= 1.29508f) {
                if (f[17] <= 1.46703f) {
                    return 5.0000f;
                } else {
                    return 5.0000f;
                }
            } else {
                if (f[29] <= 1.31404f) {
                    return 5.0000f;
                } else {
                    return 5.0000f;
                }
            }
        }
    }
}

static inline float tinyml_itree_7(const float* f) {
    if (f[50] <= 4.50810f) {
        if (f[42] <= 2.74297f) {
            if (f[28] <= 10.12417f) {
                if (f[19] <= 1.14826f) {
                    if (f[17] <= 0.11387f) {
                        if (f[25] <= 0.49018f) {
                            if (f[25] <= -0.08860f) {
                                if (f[17] <= -0.49349f) {
                                    return 12.2963f;
                                } else {
                                    return 14.0404f;
                                }
                            } else {
                                return 8.0000f;
                            }
                        } else {
                            if (f[17] <= -1.02694f) {
                                return 8.0000f;
                            } else {
                                return 8.0000f;
                            }
                        }
                    } else {
                        if (f[2] <= -0.27339f) {
                            if (f[28] <= 5.79141f) {
                                if (f[23] <= -0.56763f) {
                                    return 10.8517f;
                                } else {
                                    return 18.7004f;
                                }
                            } else {
                                if (f[17] <= 0.34115f) {
                                    return 9.0000f;
                                } else {
                                    return 9.0000f;
                                }
                            }
                        } else {
                            if (f[23] <= -0.29557f) {
                                return 8.0000f;
                            } else {
                                if (f[3] <= -0.28216f) {
                                    return 11.7066f;
                                } else {
                                    return 11.7066f;
                                }
                            }
                        }
                    }
                } else {
                    if (f[22] <= 1.62402f) {
                        if (f[17] <= 0.64045f) {
                            if (f[22] <= 1.31235f) {
                                return 8.0000f;
                            } else {
                                return 8.0000f;
                            }
                        } else {
                            if (f[22] <= 1.43969f) {
                                if (f[17] <= 1.20505f) {
                                    return 9.0000f;
                                } else {
                                    return 10.0000f;
                                }
                            } else {
                                return 8.0000f;
                            }
                        }
                    } else {
                        return 6.0000f;
                    }
                }
            } else {
                return 4.0000f;
            }
        } else {
            return 3.0000f;
        }
    } else {
        if (f[17] <= 0.13464f) {
            if (f[29] <= 1.29071f) {
                return 4.0000f;
            } else {
                return 4.0000f;
            }
        } else {
            return 3.0000f;
        }
    }
}

static inline float tinyml_itree_8(const float* f) {
    if (f[27] <= -0.19261f) {
        if (f[23] <= 0.26122f) {
            if (f[20] <= 1.22535f) {
                if (f[22] <= 0.57075f) {
                    return 5.0000f;
                } else {
                    if (f[17] <= -0.51519f) {
                        return 6.0000f;
                    } else {
                        if (f[22] <= 1.38552f) {
                            if (f[17] <= 1.27287f) {
                                return 8.0000f;
                            } else {
                                return 8.0000f;
                            }
                        } else {
                            if (f[17] <= 1.30811f) {
                                return 8.0000f;
                            } else {
                                return 8.0000f;
                            }
                        }
                    }
                }
            } else {
                if (f[29] <= 1.36253f) {
                    if (f[17] <= 1.17529f) {
                        if (f[17] <= -1.10261f) {
                            return 7.0000f;
                        } else {
                            return 7.0000f;
                        }
                    } else {
                        return 6.0000f;
                    }
                } else {
                    if (f[17] <= -0.81560f) {
                        return 6.0000f;
                    } else {
                        if (f[29] <= 1.57101f) {
                            return 7.0000f;
                        } else {
                            if (f[29] <= 1.59218f) {
                                return 8.0000f;
                            } else {
                                return 8.0000f;
                            }
                        }
                    }
                }
            }
        } else {
            if (f[31] <= -0.25887f) {
                if (f[46] <= 13.15311f) {
                    if (f[25] <= 0.68866f) {
                        if (f[3] <= -0.28163f) {
                            if (f[28] <= 10.92957f) {
                                if (f[17] <= 0.25333f) {
                                    return 18.8391f;
                                } else {
                                    return 13.5659f;
                                }
                            } else {
                                return 8.0000f;
                            }
                        } else {
                            if (f[3] <= -0.27670f) {
                                if (f[25] <= 0.14003f) {
                                    return 9.0000f;
                                } else {
                                    return 10.0000f;
                                }
                            } else {
                                return 8.0000f;
                            }
                        }
                    } else {
                        if (f[28] <= 6.41060f) {
                            if (f[15] <= -0.24737f) {
                                return 8.0000f;
                            } else {
                                if (f[17] <= -0.41338f) {
                                    return 9.0000f;
                                } else {
                                    return 9.0000f;
                                }
                            }
                        } else {
                            if (f[28] <= 9.24914f) {
                                if (f[15] <= -0.24566f) {
                                    return 9.0000f;
                                } else {
                                    return 9.0000f;
                                }
                            } else {
                                return 8.0000f;
                            }
                        }
                    }
                } else {
                    if (f[46] <= 16.06162f) {
                        return 6.0000f;
                    } else {
                        if (f[46] <= 17.88355f) {
                            return 7.0000f;
                        } else {
                            if (f[17] <= 0.33458f) {
                                return 8.0000f;
                            } else {
                                return 8.0000f;
                            }
                        }
                    }
                }
            } else {
                return 4.0000f;
            }
        }
    } else {
        if (f[22] <= 1.49717f) {
            if (f[16] <= 0.80555f) {
                return 4.0000f;
            } else {
                return 4.0000f;
            }
        } else {
            return 3.0000f;
        }
    }
}

static inline float tinyml_itree_9(const float* f) {
    if (f[27] <= -0.11000f) {
        if (f[42] <= 1.19072f) {
            if (f[28] <= 2.62653f) {
                if (f[2] <= -0.27338f) {
                    if (f[17] <= 0.93165f) {
                        if (f[18] <= 3.17976f) {
                            if (f[24] <= -0.00247f) {
                                if (f[23] <= -1.16191f) {
                                    return 9.0000f;
                                } else {
                                    return 12.5355f;
                                }
                            } else {
                                if (f[28] <= 0.45771f) {
                                    return 18.9598f;
                                } else {
                                    return 9.0000f;
                                }
                            }
                        } else {
                            if (f[29] <= -0.66200f) {
                                if (f[16] <= -0.46973f) {
                                    return 9.0000f;
                                } else {
                                    return 10.0000f;
                                }
                            } else {
                                if (f[17] <= 0.20207f) {
                                    return 10.2074f;
                                } else {
                                    return 9.0000f;
                                }
                            }
                        }
                    } else {
                        if (f[46] <= 4.54300f) {
                            if (f[23] <= -0.76598f) {
                                return 8.0000f;
                            } else {
                                if (f[18] <= 3.78145f) {
                                    return 10.2074f;
                                } else {
                                    return 9.0000f;
                                }
                            }
                        } else {
                            return 7.0000f;
                        }
                    }
                } else {
                    if (f[3] <= -0.28154f) {
                        if (f[3] <= -0.28324f) {
                            return 7.0000f;
                        } else {
                            if (f[25] <= 0.09790f) {
                                return 8.0000f;
                            } else {
                                if (f[3] <= -0.28208f) {
                                    return 10.0000f;
                                } else {
                                    return 9.0000f;
                                }
                            }
                        }
                    } else {
                        return 6.0000f;
                    }
                }
            } else {
                return 4.0000f;
            }
        } else {
            if (f[17] <= -0.30894f) {
                return 4.0000f;
            } else {
                return 4.0000f;
            }
        }
    } else {
        return 2.0000f;
    }
}

static inline float tinyml_predict_anomaly(const float* raw_features, bool* out_is_anomaly) {
    if (!raw_features) return 0.0f;

    float f[TINYML_IN_FEATURES];
    tinyml_standardize_features(raw_features, f);

    float sum_path = 0.0f;
    sum_path += tinyml_itree_0(f);
    sum_path += tinyml_itree_1(f);
    sum_path += tinyml_itree_2(f);
    sum_path += tinyml_itree_3(f);
    sum_path += tinyml_itree_4(f);
    sum_path += tinyml_itree_5(f);
    sum_path += tinyml_itree_6(f);
    sum_path += tinyml_itree_7(f);
    sum_path += tinyml_itree_8(f);
    sum_path += tinyml_itree_9(f);
    float avg_path = sum_path / (float)TINYML_NUM_ITREES;

    // Diem so bat thuong s = 2^(-E(h)/c(n))
    float anomaly_score = powf(2.0f, -avg_path / TINYML_IFOREST_CN);

    if (anomaly_score < 0.0f) anomaly_score = 0.0f;
    if (anomaly_score > 1.0f) anomaly_score = 1.0f;

    bool is_anom = (anomaly_score >= TINYML_ANOMALY_THRESHOLD);
    if (out_is_anomaly) {
        *out_is_anomaly = is_anom;
    }
    return anomaly_score;
}

// =====================================================================
// TIER 2: ATTACK CLASSIFIER ENGINE (EdgeDeepNet)
// =====================================================================
// --- Deep Learning Multi-Class Classifier (EdgeDeepNet DNN) ---
// Lưu ý: Toàn bộ trọng số và đồ thị mạng nơ-ron sâu được biên dịch thành
// TensorFlow Lite FlatBuffer trong g_classifier_tflite[] (xem tinyml_tflite_array.h).
#define TINYML_CLASSIFIER_IS_DL 1
#if __has_include("tinyml_tflite_array.h")
  #include "tinyml_tflite_array.h"
#endif

static inline int tinyml_predict_classifier(const float* raw_features, float* out_confidence) {
    if (out_confidence) *out_confidence = 1.0f;
    return TINYML_NORMAL_CLASS_IDX;
}

#endif // TINYML_MODEL_H
